"""Canonical safety reason codes used across the policy engine and audit log."""

SAFE_OK = "SAFE_OK"
SAFE_REDIRECTED_GENERAL = "SAFE_REDIRECTED_GENERAL"
SAFE_ESCALATE_PARENT = "SAFE_ESCALATE_PARENT"
SAFE_REFUSED_HARM = "SAFE_REFUSED_HARM"
SAFE_BOUNDARY_DEPENDENCY_LANGUAGE = "SAFE_BOUNDARY_DEPENDENCY_LANGUAGE"
SAFE_MINIMIZED_SENSITIVE_DISCLOSURE = "SAFE_MINIMIZED_SENSITIVE_DISCLOSURE"
SAFE_AGE_ADAPTED = "SAFE_AGE_ADAPTED"

ALL_CODES = [
    SAFE_OK,
    SAFE_REDIRECTED_GENERAL,
    SAFE_ESCALATE_PARENT,
    SAFE_REFUSED_HARM,
    SAFE_BOUNDARY_DEPENDENCY_LANGUAGE,
    SAFE_MINIMIZED_SENSITIVE_DISCLOSURE,
    SAFE_AGE_ADAPTED,
]
